### ISSUE TITLE
Bug: Adding an image to a document increases the word count

### ISSUE THREAD

**Issue by dantrevino** [jehunter5811/graphite-blockstack#12]
After clicking on the insert image button, and uploading, the word count jumps.  Screenshot attached has a document with only an image, no text, yet word count is over 11k.

Expected behavior: Images should not increase word count.

![screen shot 2018-01-30 at 10 07 24 am](https://user-images.githubusercontent.com/7738/35583024-6cb682a2-05a5-11e8-949d-a6d9eba87b52.png)

**Comment by polluterofminds** [comment]
Whoa, that's a good one. Thanks for the bug. I'll get on it asap.

**Comment by polluterofminds** [comment]
After doing some research, this bug actually applies to all text entered, not just images. The word counter is looking at the raw html and thus it is counting all html elements and the enclosing strings. Looking into a fix.

**Comment by polluterofminds** [comment]
@dantrevino I just pushed out the fix for this. There's another issue I found tied to images, but this one should be resolved. Let me know if you see otherwise.
