### ISSUE TITLE
How can I get to spreadsheets I had in old version?

### ISSUE THREAD

**Issue by MedBTG** [jehunter5811/graphite-blockstack#24]
How can I get to spreadsheets I had in old version?  And can you explain how you will be dealing with spreadsheets in the future.  Trying to understand where you are going with product.  Spreadsheets were important.  Thanks

**Comment by polluterofminds** [comment]
This is the old repository for the Graphite project. The new repo is here: https://github.com/graphite-docs/graphite 

You can still access your old Sheets by going to https://app.graphitedocs.com/sheets, however, you will not be able to create new ones. Here's a blog post that talks about the direction: 

https://medium.com/the-lead/the-end-of-graphite-sheets-c67ce7524364
