### ISSUE TITLE
Bug: Unidentified function error

### ISSUE THREAD

**Issue by 20jsg17** [jehunter5811/graphite-blockstack#8]
Justin - left a note on the Blockstack forum re: post here - This is what I encountered when I tried to select a new Sheet:
![graphite- sheets feedback](https://user-images.githubusercontent.com/33142327/35179466-8f55daee-fd60-11e7-8b88-485da53af3c3.png)

Will keep checking it out - great app.

**Comment by polluterofminds** [comment]
@20jsg17 Did you get that error on the initial sheet creation or was it after you created a sheet and tried to access it again? If it was after you created and tried to access it, do you remember if you had tested out a formula?

**Comment by 20jsg17** [comment]
Inital sheet creation: Selected the "+" New Sheet, new sheet comes up then that pop-up appears (nothing created on sheets before).  Make sense?

**Comment by polluterofminds** [comment]
Thanks @20jsg17! Can you tell me what version of the Blockstack Browser you are using? Have you downloaded the most recent one from blockstack.org?

**Comment by polluterofminds** [comment]
I cannot reproduce this, so please make sure you are using the most recent browser. It should be 0.22 or higher.

**Comment by 20jsg17** [comment]
The version I have been using is 0.22.1

**Comment by 20jsg17** [comment]
FYI - Another run after restore of browser  - same version 0.22.1 - accessing Sheets:
![graphite_bug unidentified function error 8_1](https://user-images.githubusercontent.com/33142327/35197957-486e0f40-fead-11e7-98b0-f463d6af0776.png)
![graphite_bug unidentified function error 8_2](https://user-images.githubusercontent.com/33142327/35197958-487e1b92-fead-11e7-94a4-3ee26532907f.png)
![graphite_bug unidentified function error 8_3](https://user-images.githubusercontent.com/33142327/35197959-488cef32-fead-11e7-9112-2b76537da6d3.png)

**Comment by polluterofminds** [comment]
Thanks. It looks like you're using Safari, so I'm going to see if I can replicate the issue there.

**Comment by polluterofminds** [comment]
@20jsg17 you are the man for catching this. Got a fix coming. I was using the .finally promise which is not yet supported in Safari:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

Fix coming soon. Will update you.

**Comment by 20jsg17** [comment]
I try and switch browsers (Firefox, chrome, brave, safari for the most part) from time to time to make sure I can use in that particular browser (portability?)  Make sense?  Anyway, let me know if I can help you in the promotion of this or blockstack in general.

**Comment by 20jsg17** [comment]
At this point I have only used it in Safari.  Perhaps I should try it in other browsers.  Your thoughts?

**Comment by polluterofminds** [comment]
@20jsg17 It will likely work for you in Safari now, but that fix broke formula support in Chrome. Still working, but feel free to use it in Safari now :)

**Comment by polluterofminds** [comment]
Alright, looks like we're good to go now. Feel free to confirm at your convenience. I will hold this issue open until I hear back from you.

**Comment by 20jsg17** [comment]
Checked on two different machines running Safari and it is working now - great.  Now, on sharing (tried it btw. the two machines and says cannot find user I.D. of I.D. that shred the file (it is typed correctly...).  Do you want me to open another thread?

**Comment by 20jsg17** [comment]
FYI - re: sharing issue happens on both machines.

**Comment by polluterofminds** [comment]
Sorry you hit another issue. Yes, please open another issue if you don't mind. And can you drop the your blockstack id and the I'd you're trying to look up into the issue?

**Comment by 20jsg17** [comment]
Perhaps the reason is that the I.D. is not an I.D. from the BNS (.id).  Thoughts?  And on another note, anytime you want some beta testing done on something, let me know (I will do my best to help).

**Comment by polluterofminds** [comment]
Thanks @20jsg17! I might have something soon to test. And yes, it has to be a Blockstack ID that you look up. That's the only way Blockstack stored files can be shared. Thanks for helping me track down these issues.
