### ISSUE TITLE
Copyediting Error

### ISSUE THREAD

**Issue by Anastik** [jehunter5811/graphite-blockstack#9]
On the Graphite "Get Started" Page there is a spelling error. It should be spelled "Encrypted."
![screen shot 2018-01-20 at 12 58 12 pm](https://user-images.githubusercontent.com/33998307/35188414-99ea991e-fde1-11e7-974b-e97083259a60.png)

**Comment by polluterofminds** [comment]
Good catch @Anastik! I've fixed this now, thanks.
